# Generated by Django 5.2.4 on 2025-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectacle',
            name='full_description',
            field=models.TextField(default='no full description yet'),
        ),
    ]
