# Generated by Django 5.2.4 on 2025-10-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_spectacle_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectacle',
            name='description',
            field=models.CharField(default='no description yet', max_length=50),
        ),
    ]
