# Generated by Django 5.2.4 on 2025-10-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_partner_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spectacle',
            options={'ordering': ['date']},
        ),
    ]
