# Generated by Django 5.2.4 on 2025-10-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_alter_spectacle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spectacle',
            options={'ordering': ['-date']},
        ),
    ]
